/**
 * Single-token boosts for words that are not (yet) in `keyboard-terminology`.
 * Keeps the rules parser useful on short sentences without growing the community dictionary.
 */

import type { TraitMetadata } from "@/recommendation-engine/traits";

/** Normalized token → boost (after phrase stripping). */
export const WORD_BOOSTS: Record<string, TraitMetadata> = {
  deep: { deep_sound: 5 },
  deeper: { deep_sound: 6 },
  thock: { deep_sound: 4, soft: 2 },
  warm: { deep_sound: 4, soft: 2 },
  bright: { clacky: 5, deep_sound: 1 },
  sharp: { clacky: 5, firm: 2 },
  pingy: { clacky: 6, firm: 2 },
  smooth: { smooth: 5 },
  linear: { smooth: 6, tactile_strength: -1 },
  tactile: { tactile_strength: 5, smooth: 2 },
  quiet: { soft: 4, clacky: -2 },
  loud: { clacky: 4, firm: 2 },
  firm: { firm: 5 },
  stiff: { firm: 5 },
  soft: { soft: 4 },
  도각도각: { deep_sound: 6, soft: 2, firm: 2 },
  도각: { deep_sound: 5, soft: 2 },
  보글보글: { soft: 6, smooth: 4, clacky: -2 },
  서걱서걱: { smooth: -3, tactile_strength: 4, firm: 3, clacky: 3 },
  서걱: { smooth: -2, tactile_strength: 3, clacky: 2 },
  저음: { deep_sound: 6 },
  고음: { clacky: 6, deep_sound: 1 },
  묵직한: { deep_sound: 4, firm: 3 },
  푹신한: { soft: 6, firm: -1 },
  쫀득한: { smooth: 4, soft: 3, tactile_strength: 2 },
  통울림: { deep_sound: 3, clacky: 3, soft: -2 },
  조용한: { soft: 4, clacky: -2 },
  차분한: { soft: 3, clacky: -1 },
  단단한: { firm: 6, soft: -1 },
  빳빳한: { firm: 6, soft: -1 },
  강성: { firm: 5, soft: -1 },
  유연한: { soft: 4, smooth: 2, firm: -1 },
  플렉스: { soft: 4, smooth: 2, firm: -1 },
  택타일: { tactile_strength: 6, smooth: -1 },
  구분감: { tactile_strength: 5, firm: 2 },
  리니어: { smooth: 6, tactile_strength: -2 },
  매끈한: { smooth: 5, soft: 2 },
  저소음: { soft: 4, clacky: -2 },
  정숙한: { soft: 4, clacky: -2 },
  쨍한: { clacky: 5, deep_sound: 1 },
  또렷한: { clacky: 4, firm: 2 },
  맑은: { clacky: 4, deep_sound: 1 },
  무거운: { firm: 4, soft: -1, tactile_strength: 2 },
  가벼운: { soft: 2, smooth: 2, tactile_strength: -1 },
  탄성있는: { soft: 4, smooth: 3, firm: -1 },
  탱글한: { soft: 3, smooth: 3, tactile_strength: 1 },
  또각또각: { deep_sound: 4, firm: 3, clacky: 2 },
  도독도독: { deep_sound: 5, soft: 2, firm: 2 },
  먹먹한: { soft: 4, deep_sound: 2, clacky: -2 },
  울림이큰: { deep_sound: 2, clacky: 3, soft: -1 },
  텅빈소리: { deep_sound: 2, clacky: 3, soft: -1 },
  // Phase E — keycap material / profile cues (map into engine axes used by keycap ranking).
  pbt: { soft: 4, clacky: -2, deep_sound: 2 },
  abs: { clacky: 4, firm: 1, soft: -1 },
  gmk: { clacky: 3, firm: 1 },
  doubleshot: { clacky: 3, soft: -1 },
  "이중사출": { clacky: 3, soft: -1 },
  dyesub: { soft: 4, clacky: -2, deep_sound: 2 },
  "염료승화": { soft: 4, clacky: -2, deep_sound: 2 },
  keycap: { soft: 1, clacky: 1 },
  키캡: { soft: 1, clacky: 1 },
};
